language: python
python:
  - 2.6
  - 2.7
env:
  # test the standalone functionality
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook DJANGO=1.3.7 MODE=standalone CUSTOM_USER_MODEL=0
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook DJANGO=1.4.5 MODE=standalone CUSTOM_USER_MODEL=0
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook DJANGO=1.5.1 MODE=standalone CUSTOM_USER_MODEL=0
  - REQUIREMENTS=development SETTINGS=facebook_example.settings TESTS=django_facebook open_facebook DJANGO=1.5.1 MODE=standalone CUSTOM_USER_MODEL=1
  # test django registration integration
  - REQUIREMENTS=django_registration SETTINGS=facebook_example.django_registration_settings TESTS=django_facebook open_facebook DJANGO=1.3.7 MODE=django_registration CUSTOM_USER_MODEL=0
  - REQUIREMENTS=django_registration SETTINGS=facebook_example.django_registration_settings TESTS=django_facebook open_facebook DJANGO=1.4.5 MODE=django_registration CUSTOM_USER_MODEL=0
  # userena currently doesn't support testing :(
postgres:
  adapter: sqlite3
  database: django_fb_test
install:
  - pip install pep8 --use-mirrors
  - pip install coverage
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
  - pip install -r facebook_example/requirements/$REQUIREMENTS.txt --use-mirrors -I
  - pip install -q Django==$DJANGO --use-mirrors -I
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 django_facebook open_facebook"
#  - pyflakes -x W src
script:
  - pip install -e .
  - cd facebook_example
  - coverage run manage.py test $TESTS --settings=$SETTINGS
  - coverage report