language: python
python:
  - 2.6
  - 2.7
env:
  - REQUIREMENTS=development.txt SETTINGS=facebook_example.settings TESTS=django_facebook
postgres:
  adapter: sqlite3
  database: django_fb_test
install:
  - python setup.py install
  - pip install -r facebook_example/requirements/$REQUIREMENTS.txt --use-mirrors -I
script:
  - cd tests
  - python manage.py test $TESTS --settings=$SETTINGS